cad_design_task:
  description: >
    Interpret the user's prompt describing a CAD design into engineering specifications.
    User prompt: {user_prompt}.
    Identify geometry, dimensions, and constraints. 
  expected_output: >
    A detailed engineering specification for the CAD design.
  agent: cad_system_designer

openscad_scripting_task:
  description: >
    With the CAD specification, first, you must consult the provided documentation and cheatsheet
    to find the relevant information and functions for the design.
    Then, think about the strategy to design the object in OpenSCAD with everything you know.
    Then, you must generate a valid OpenSCAD script using the correct functions.
    Do not include pseudocode or non-existent functions.
    The script must be directly usable in OpenSCAD without modification.
    You must follow these rules:
    - All variable assignments must happen at the top of the module, before any geometry.
    - Test expressions for divisions and nested rotations.
    - DO NOT include markdown formatting (like ```) or backticks.
  expected_output: >
    A clean, error-free OpenSCAD script using correct syntax.
    The code must be directly copy-pasteable and should compile in OpenSCAD.
  agent: openscad_code_engineer


debug_openscad_task:
  description: >
    Review the OpenSCAD script provided and the result of its compilation.
    If the validator confirms it is valid, simply return the same script.
    If the validator reports syntax errors, analyze the error message and regenerate a corrected version of the script.
    Ensure your output is clean, with correct OpenSCAD syntax, and does not include markdown formatting or backticks.

  expected_output: >
    A fully corrected OpenSCAD script that compiles without syntax errors.
    Only output the code — no extra explanation.
  agent: openscad_code_engineer