cad_design_task:
  description: >
    Interpret the user's prompt describing a CAD design into engineering specifications.
    User prompt: {user_prompt}
    Identify geometry, dimensions, and constraints. 
    List the basic steps to create the design in a CAD software.
  expected_output: >
    A detailed engineering specification for the CAD design.
  agent: cad_system_designer

openscad_scripting_task:
  description: >
    Convert the engineering specification into OpenSCAD code.
    Make sure the code is efficient and easy to understand.
  expected_output: >
    A fully fledged OpenSCAD script that can be used to generate the CAD design.
    DO NOT include markdown formatting or backticks.
  agent: openscad_code_engineer
